version: '3.2'
volumes:
    postgres-data:
services:
    db:
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
    web:
        build:
            context: .
            dockerfile: Dockerfile
            # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        command: "foreman start" 
        volumes:
            - .:/ik
        ports:
            - "3000:3000"
            - "5000:5000"
            - "3035:3035"
        depends_on:
            - db                             
